// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  blogs: create.doc("blogs", {"commercial.mdx": () => import("../content/blog/commercial.mdx?collection=blogs"), "question.mdx": () => import("../content/blog/question.mdx?collection=blogs"), }),
  docs: create.doc("docs", {"AI-introduction.mdx": () => import("../content/docs/AI-introduction.mdx?collection=docs"), "introduction.mdx": () => import("../content/docs/introduction.mdx?collection=docs"), "wechat.mdx": () => import("../content/docs/wechat.mdx?collection=docs"), "database/mongodb.mdx": () => import("../content/docs/database/mongodb.mdx?collection=docs"), "components/Case.mdx": () => import("../content/docs/components/Case.mdx?collection=docs"), "components/ClipboardBtn.mdx": () => import("../content/docs/components/ClipboardBtn.mdx?collection=docs"), "components/Faq.mdx": () => import("../content/docs/components/Faq.mdx?collection=docs"), "components/FaqList.mdx": () => import("../content/docs/components/FaqList.mdx?collection=docs"), "components/FeatureCard.mdx": () => import("../content/docs/components/FeatureCard.mdx?collection=docs"), "components/FeatureGrid.mdx": () => import("../content/docs/components/FeatureGrid.mdx?collection=docs"), "components/Features.mdx": () => import("../content/docs/components/Features.mdx?collection=docs"), "components/Footer.mdx": () => import("../content/docs/components/Footer.mdx?collection=docs"), "components/Header.mdx": () => import("../content/docs/components/Header.mdx?collection=docs"), "components/Hero.mdx": () => import("../content/docs/components/Hero.mdx?collection=docs"), "components/LandingPage.mdx": () => import("../content/docs/components/LandingPage.mdx?collection=docs"), "components/Price.mdx": () => import("../content/docs/components/Price.mdx?collection=docs"), "components/Table.mdx": () => import("../content/docs/components/Table.mdx?collection=docs"), "start/github.mdx": () => import("../content/docs/start/github.mdx?collection=docs"), "start/preparation.mdx": () => import("../content/docs/start/preparation.mdx?collection=docs"), "start/start.mdx": () => import("../content/docs/start/start.mdx?collection=docs"), "start/vercel.mdx": () => import("../content/docs/start/vercel.mdx?collection=docs"), "features/email.mdx": () => import("../content/docs/features/email.mdx?collection=docs"), "features/google.mdx": () => import("../content/docs/features/google.mdx?collection=docs"), "features/phone.mdx": () => import("../content/docs/features/phone.mdx?collection=docs"), "features/r2.mdx": () => import("../content/docs/features/r2.mdx?collection=docs"), "features/wechatLogin.mdx": () => import("../content/docs/features/wechatLogin.mdx?collection=docs"), "pay/stripe.mdx": () => import("../content/docs/pay/stripe.mdx?collection=docs"), "pay/wechat.mdx": () => import("../content/docs/pay/wechat.mdx?collection=docs"), }),
};
export default browserCollections;